apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab99-frontend
  labels:
    app: lab99-frontend
spec:
  selector:
    matchLabels:
      app: lab99-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: lab99-frontend
    spec:
      containers:
        - name: lab99-frontend
          image: happycloudpak/lab99-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
