apiVersion: v1
kind: Service
metadata:
  name: lab99-front-svc
spec:
  type: NodePort
  selector:
    appname: lab99-frontend
  ports:
    - name: port-lab99-frontend
      port: 8080
      targetPort: 3000
