apiVersion: v1
kind: Service
metadata:
  name: lab99-frontend-svc
spec:
  type: NodePort
  selector:
    app: lab99-frontend
  ports:
    - name: port-lab99-frontend
      port: 8081
      targetPort: 3000
